### ISSUE TITLE
Todo List 

### ISSUE THREAD

**Issue by Mcamilo** [Mcamilo/AskReddit-video-bot#2]
- [x] **Reddit**
  - [x] Collect _n_ most recent posts from the  AskReddit subreddit
  - [x] Allow post selection
  - [x] Collect comments on a selected post
  - [x] Save in memory
  - [x] Filter Comments by size
  - [ ] Dynamically add subreddits to fetch
---
- [ ] ** Text **
- [ ] Filter cuss words
- [ ] Eliminate Text noise (Characters, 'edits', links, etc) 

---

- [x] **Frames**
  - [x] Retrieve selected thread (list of comments and replies)
  - [x] Write each sentence in an image (frame)
  - [x] Save frames from the same thread in a single directory
  - [x] Improve the Comment Template
  - [x] Create Question Template
  - [ ] Add Gold and Rewards to the frame design

---

  - [x] **Audio**
  - [x]  Transform thread text to speech (T2S)
  - [x]  Question audio
  - [ ]  Dependency Injection 
---

  - [x] **Video**
  - [x] Pair frames and audio
  - [x] Add animations (cuts)
  - [x] Background loop for the entire length of the video
  - [x]  Merge concatenated audio with background music
  - [x] Synchronize Features
  - [x] Question

---

  - [ ] **Youtube**
  - [ ] Authenticate with OAuth
  - [ ] Video upload 
  - [ ] Dynamically create Thumbnail
  - [ ] Thumbnail Upload (Reddify)

---
